inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'services/**/*'
    - 'documentation/**/*'
    - 'core-frontend/**/*'
    - 'db/schema.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
