inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable
  Exclude:
    - 'bin/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
