inherit_from: .rubocop_todo.yml
inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable
  Exclude:
    - services/**/*
    - vendor/**/*
    - db/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/IndentationWidth:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
