version: '3.9'

services:
  core-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:     
      - pg
      - rabbitmq
      - redis
      - sidekiq
    ports:
      - "3000:3000"
    volumes:
      - .:/core-backend
      - gem_cache:/core-backend/vendor/bundle
    env_file:
      - .env.dev
      - .env.dev.local
    tty: true
    stdin_open: true
    environment:      
      RAILS_ENV: development
      DB_HOST: pg
      BUNDLE_PATH: /core-backend/vendor/bundle
      PORT: 3000

  core-frontend:
    build:
      context: ./core-frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - core-backend
    ports:
      - "4000:4000"
    volumes:
      - ./core-frontend:/core-frontend
      - node_cache:/core-frontend/node_modules
    environment:
      NODE_ENV: development
      PORT: 4000

  pg:
    image: postgres:14.3-alpine
    restart: always
    env_file: .env.dev
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    env_file: 
      - .env.dev
      - .env.dev.local
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf", "--requirepass ${REDIS_PASSWORD}" ]

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/core
    env_file: .env.dev

volumes:
  gem_cache:
  node_cache:
  db_data:
  rabbitmq_data:
  rabbitmq_log:
