version: '3.9'

services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:     
      - pg
    ports:
      - "3000:3000"
    volumes:
      - .:/core
      - gem_cache:/usr/local/bundle/gems
    env_file: .env.dev
    tty: true
    stdin_open: true
    environment:
      DB_PASSWORD: password
      DB_USER: postgres
      RAILS_ENV: development
      DB_HOST: pg

  pg:
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  gem_cache:
  db_data: