FROM ruby:3.1.1-alpine

RUN apk --update add build-base tzdata postgresql-dev postgresql-client

ENV APP_DIR /core-backend

WORKDIR $APP_DIR

COPY Gemfile ./
COPY Gemfile.lock ./

ARG RAILS_ENV
ENV RACK_ENV=$RAILS_ENV

RUN gem install bundler

RUN bundle install --path=vendor/bundle

COPY . ./

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

CMD bundle exec rails s -b '0.0.0.0'
