---
openapi: 3.0.1
info:
  title: Core API V1
  version: v1
paths:
  "/api/v1/users":
    post:
      summary: Updates a user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                is_enabled:
                  type: boolean
              required:
              - email
              - is_enabled
  "/build-info":
    get:
      summary: gets the build info
      tags:
      - Info
      responses:
        '200':
          description: info received
servers:
- url: https://qa-core-api.nordhen.com
- url: http://localhost:3000
components:
  schemas:
    info:
      type: object
      properties:
        build_id:
          type: string
        build_date:
          type: string
        build_branch:
          type: string
      required:
      - build_id
      - build_date
      - build_branch
