default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") { "core" } %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "core_development" } %>
test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "core_testing" } %>
qa:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "core" } %>
staging:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "core" } %>
production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "core" } %>
