default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV("DB_USERNAME") %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV("DB_HOST") %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
test:
  <<: *default
  database: core_backend_test
production:
  <<: *default
  database: core_backend_production
